'use client'

import Link from 'next/link'
import { PrimaryButton } from '@/components/ui/button'
import { ArrowLeft, CheckCircle2, GraduationCap } from 'lucide-react'
import { useState } from 'react'

const universities = ['UNSA', 'UCSM', 'Universidad Católica San Pablo', 'UTP', 'Universidad La Salle']

export default function StudentRegistration() {
  const [submitted, setSubmitted] = useState(false)
  if (submitted) return <main className="grid min-h-screen place-items-center bg-secondary/30 px-5"><section className="w-full max-w-md rounded-3xl bg-card p-8 text-center ring-1 ring-black/[0.06]"><CheckCircle2 className="mx-auto size-14 text-primary"/><h1 className="mt-5 text-2xl font-bold">Verifica tu correo electrónico</h1><p className="mt-3 leading-7 text-muted-foreground">Te enviamos un enlace para confirmar tu cuenta. Luego podrás guardar alojamientos y solicitar visitas.</p><Link href="/buscar" className="mt-7 inline-flex rounded-full bg-primary px-6 py-3 font-semibold">Explorar alojamientos</Link></section></main>
  return <main className="min-h-screen bg-secondary/30 px-5 py-8"><div className="mx-auto max-w-2xl"><Link href="/registro" className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16}/> Volver</Link><section className="mt-8 rounded-3xl bg-card p-6 shadow-sm ring-1 ring-black/[0.06] sm:p-10"><div className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-2xl bg-primary/15 text-primary"><GraduationCap/></span><div><p className="text-sm font-semibold text-foreground">Cuenta de estudiante</p><h1 className="text-3xl font-bold">Encuentra tu próximo hogar</h1></div></div><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }} className="mt-8 grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Nombre<input required className="field" placeholder="Tu nombre"/></label><label className="grid gap-2 text-sm font-semibold">Apellido<input required className="field" placeholder="Tu apellido"/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Correo electrónico<input required type="email" className="field" placeholder="nombre@universidad.edu.pe"/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Contraseña<input required minLength={8} type="password" className="field" placeholder="Mínimo 8 caracteres"/></label><label className="grid gap-2 text-sm font-semibold">Universidad<select required className="field" defaultValue=""><option value="" disabled>Selecciona tu universidad</option>{universities.map((item) => <option key={item}>{item}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Campus<input required className="field" placeholder="Ej. Campus principal"/></label><label className="grid gap-2 text-sm font-semibold">Facultad<input required className="field" placeholder="Ej. Ingeniería"/></label><label className="grid gap-2 text-sm font-semibold">Carrera<input required className="field" placeholder="Ej. Arquitectura"/></label><label className="flex gap-3 text-sm leading-6 text-muted-foreground sm:col-span-2"><input required type="checkbox" className="mt-1 accent-primary"/>Acepto los términos y condiciones y la política de privacidad.</label><PrimaryButton type="submit" className="sm:col-span-2">Crear cuenta</PrimaryButton></form></section></div></main>
}

