'use client'

import Link from 'next/link'
import { BrandLogo } from '@/components/BrandLogo'
import { useState } from 'react'
import { ArrowLeft, Bath, BedDouble, CalendarDays, Check, Heart, MapPin, MessageCircle, Send, ShowerHead, Sparkles, Wifi, X } from 'lucide-react'

export default function PropertyDetail() {
  const [saved, setSaved] = useState(false)
  const [visitOpen, setVisitOpen] = useState(false)
  const [sent, setSent] = useState(false)

  return <div className="min-h-screen pb-20 lg:pb-0">
    <header className="border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-7xl flex-wrap items-center justify-between gap-2 px-4 py-2 lg:px-8"><BrandLogo compact /><Link href="/buscar" className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16}/> Volver a resultados</Link></div></header>
    <main className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8 lg:py-8">
      <div className="grid gap-2 overflow-hidden rounded-2xl sm:gap-3 md:grid-cols-[1.5fr_1fr] md:grid-rows-2"><img src="/habitat-room.png" alt="Habitación privada amoblada" className="h-64 w-full object-cover sm:h-80 md:row-span-2 md:h-full"/><img src="/habitat-hero.png" alt="Espacio común del alojamiento" className="hidden h-44 w-full object-cover md:block"/><div className="hidden overflow-hidden md:block"><img src="/habitat-room.png" alt="Detalle del alojamiento" className="h-full w-full object-cover"/></div></div>
      <div className="mt-7 grid gap-10 lg:grid-cols-[1fr_350px] lg:mt-10"><div>
        <div className="flex flex-wrap items-center gap-2 text-sm"><span className="rounded-full bg-primary/20 px-3 py-1.5 font-semibold"><Check size={14} className="mr-1 inline"/>Verificado</span><span className="rounded-full bg-secondary px-3 py-1.5">Disponible</span></div>
        <div className="flex items-start justify-between gap-4"><div><h1 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Habitación privada amoblada cerca de la UCSM</h1><p className="mt-3 flex items-center gap-2 text-muted-foreground"><MapPin size={17}/> Yanahuara, Arequipa · 1.4 km de la UCSM</p></div><button aria-label={saved ? 'Quitar de favoritos' : 'Guardar en favoritos'} onClick={() => setSaved(!saved)} className="mt-4 grid size-11 shrink-0 place-items-center rounded-full border border-border transition hover:border-primary hover:text-primary"><Heart size={20} className={saved ? 'fill-primary text-primary' : ''}/></button></div>
        <div className="my-7 grid grid-cols-2 gap-3 sm:grid-cols-4"><Info icon={<BedDouble/>} label="Tipo" value="Individual"/><Info icon={<Sparkles/>} label="Amoblado" value="Sí"/><Info icon={<ShowerHead/>} label="Baño" value="Privado"/><Info icon={<CalendarDays/>} label="Disponible" value="15 oct."/></div>
        <section className="border-t border-border pt-7"><h2 className="text-xl font-bold">Lo que incluye</h2><div className="mt-5 grid grid-cols-2 gap-4 text-sm sm:grid-cols-3"><Service icon={<Wifi/>} text="WiFi"/><Service icon={<span>◉</span>} text="Agua incluida"/><Service icon={<Sparkles/>} text="Luz incluida"/><Service icon={<Bath/>} text="Cocina"/><Service icon={<span>▣</span>} text="Escritorio"/><Service icon={<BedDouble/>} text="Cama y armario"/></div></section>
        <section className="mt-8 border-t border-border pt-7"><h2 className="text-xl font-bold">Ubicación</h2><div className="mt-4 flex min-h-40 items-center justify-center rounded-2xl bg-secondary p-6 text-center"><div><MapPin className="mx-auto text-primary" size={30}/><p className="mt-2 font-semibold">Yanahuara, Arequipa</p><p className="mt-1 text-sm text-muted-foreground">1.4 km · 18 min caminando a la UCSM</p></div></div></section>
        <section className="mt-8 border-t border-border pt-7"><h2 className="text-xl font-bold">Tu anfitrión</h2><div className="mt-4 flex items-center gap-4"><div className="grid size-14 place-items-center rounded-full bg-primary text-lg font-bold">CM</div><div><p className="font-semibold">Carlos M.</p><p className="text-sm text-muted-foreground">Propietario verificado · Miembro desde 2026</p></div></div></section>
      </div><aside className="hidden lg:block"><ContactPanel onVisit={() => setVisitOpen(true)} sent={sent} onContact={() => setSent(true)}/></aside></div>
    </main>
    <div className="fixed inset-x-0 bottom-0 z-20 flex items-center justify-between gap-4 border-t border-border bg-background/95 px-4 py-3 backdrop-blur lg:hidden"><div><p className="text-lg font-bold">S/ 650 <span className="text-xs font-normal text-muted-foreground">/ mes</span></p><p className="text-xs text-muted-foreground">Yanahuara, Arequipa</p></div><button onClick={() => setSent(true)} className="flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground shadow-lg"><MessageCircle size={17}/> Contactar</button></div>
    {visitOpen && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-foreground/40 p-4"><div className="w-full max-w-md rounded-3xl bg-background p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Solicitar una visita</h2><button aria-label="Cerrar" onClick={() => setVisitOpen(false)}><X/></button></div><p className="mt-2 text-sm text-muted-foreground">Coordina una visita con Carlos para conocer el alojamiento.</p><div className="mt-5 space-y-4"><label className="block text-sm font-semibold">Fecha<input type="date" className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-3"/></label><label className="block text-sm font-semibold">Hora<input type="time" className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-3"/></label><label className="block text-sm font-semibold">Mensaje<textarea className="mt-2 min-h-24 w-full rounded-xl border border-input bg-background px-3 py-3" placeholder="Cuéntale cuándo te gustaría visitarlo..."/></label><button onClick={() => { setVisitOpen(false); setSent(true) }} className="flex w-full items-center justify-center gap-2 rounded-full bg-primary py-3 font-bold text-primary-foreground"><Send size={16}/> Enviar solicitud</button></div></div></div>}
    {sent && <div className="fixed bottom-24 left-1/2 z-40 flex -translate-x-1/2 items-center gap-3 rounded-full bg-foreground px-5 py-3 text-sm font-semibold text-background shadow-xl lg:bottom-6"><Check size={17} className="text-primary"/> Solicitud enviada. Te contactaremos pronto.</div>}
  </div>
}
function ContactPanel({onVisit,onContact,sent}:{onVisit:()=>void,onContact:()=>void,sent:boolean}) { return <div className="sticky top-6 rounded-3xl border border-border bg-card p-6 shadow-sm"><p className="text-2xl font-bold">S/ 650 <span className="text-sm font-normal text-muted-foreground">/ mes</span></p><p className="mt-1 text-sm text-muted-foreground">Sin comisión para estudiantes</p><button onClick={onContact} className="mt-6 flex w-full items-center justify-center gap-2 rounded-full bg-primary py-3.5 font-bold text-primary-foreground shadow-md transition hover:-translate-y-0.5 hover:shadow-lg"><MessageCircle size={18}/> {sent ? 'Solicitud enviada' : 'Contactar al propietario'}</button><button onClick={onVisit} className="mt-3 w-full rounded-full border border-border py-3.5 font-semibold transition hover:border-primary hover:text-primary">Solicitar visita</button><p className="mt-5 text-center text-xs text-muted-foreground">Nunca compartimos tu información sin tu permiso.</p></div>}
function Info({icon,label,value}:{icon:React.ReactNode,label:string,value:string}){return <div className="rounded-2xl bg-secondary p-4"><div className="mb-3 text-primary">{icon}</div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
function Service({icon,text}:{icon:React.ReactNode,text:string}){return <div className="flex items-center gap-3"><span className="text-primary">{icon}</span>{text}</div>}
