'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'

export default function NewListingPage() {
  const router = useRouter(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget); const payload = { title: form.get('title'), description: form.get('description'), roomType: form.get('roomType'), price: Number(form.get('price')), address: form.get('address'), location: { lat: -16.3989, lng: -71.535 }, amenities: String(form.get('amenities') || '').split(',').map(item => item.trim()).filter(Boolean), contact: { phone: form.get('phone') } }; const response = await fetch('/api/listings', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(payload) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error || 'No se pudo publicar.'); return } router.push('/dashboard') }
  return <main className="mx-auto max-w-2xl px-5 py-12"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-primary">Para propietarios</p><h1 className="mt-2 text-3xl font-bold">Publica tu alojamiento</h1></div><Link href="/dashboard" className="text-sm font-semibold">Volver</Link></div><form onSubmit={submit} className="mt-8 space-y-5 rounded-3xl border border-border p-7"><label className="block text-sm font-semibold">Título<input required name="title" placeholder="Habitación amoblada cerca de la UCSM" className="mt-2 w-full rounded-xl border border-input px-3 py-3 font-normal"/></label><label className="block text-sm font-semibold">Descripción<textarea name="description" rows={4} className="mt-2 w-full rounded-xl border border-input px-3 py-3 font-normal"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Tipo<select name="roomType" className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-3 font-normal"><option value="private">Habitación privada</option><option value="shared">Habitación compartida</option></select></label><label className="block text-sm font-semibold">Precio mensual<input required min="0" type="number" name="price" className="mt-2 w-full rounded-xl border border-input px-3 py-3 font-normal"/></label></div><label className="block text-sm font-semibold">Dirección<input required name="address" placeholder="Yanahuara, Arequipa" className="mt-2 w-full rounded-xl border border-input px-3 py-3 font-normal"/></label><label className="block text-sm font-semibold">Servicios separados por coma<input name="amenities" placeholder="WiFi, amoblado, agua incluida" className="mt-2 w-full rounded-xl border border-input px-3 py-3 font-normal"/></label><label className="block text-sm font-semibold">Teléfono de contacto<input name="phone" className="mt-2 w-full rounded-xl border border-input px-3 py-3 font-normal"/></label>{error&&<p className="text-sm text-red-600">{error}</p>}<button disabled={loading} className="w-full rounded-full bg-primary py-3 font-bold text-primary-foreground disabled:opacity-60">{loading?'Publicando...':'Publicar alojamiento'}</button></form></main>
}